version: 2

sources:
  - name: rawdatalabeling
    database: workspace
    schema: rawdatalabeling
    tables:
      - name: t12|0925|skytop
      - name: t12|022023|preserveatgreison
      - name: t12|1223|junctionatvinings
      - name: t12|0123|eastponcevillage
