version: 2

sources:
  - name: rawdata
    database: dealio_emilio
    schema: rawdata
    tables:
      - name: t12|022023|preserve_at_greison_trail
      - name: t12|0825|skytop

  - name: rawdatalabeling
    database: dealio_emilio
    schema: rawdatalabeling
    tables:
      - name: t12|0825|skytop
